// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TesteAPI.ContextoDeDados;

namespace TesteAPI.Migrations.ContextCatmasMigrations
{
    [DbContext(typeof(ContextCatmas))]
    [Migration("20201116033233_Alteracao")]
    partial class Alteracao
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("TesteAPI.Model.ItemCatalogo", b =>
                {
                    b.Property<long>("Sequencial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<string>("DescricaoBasica")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Sequencial");

                    b.ToTable("TB_Item", "catmas");
                });
#pragma warning restore 612, 618
        }
    }
}
