// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TesteAPI.ContextoDeDados;

namespace TesteAPI.Migrations.ContextCatmasMigrations
{
    [DbContext(typeof(ContextCatmas))]
    [Migration("20201115211456_InicialProjeto")]
    partial class InicialProjeto
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("TesteAPI.Model.ItemCatalogo", b =>
                {
                    b.Property<int>("Sequencial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("DescricaoBasica")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Sequencial");

                    b.ToTable("Item", "catmas");
                });
#pragma warning restore 612, 618
        }
    }
}
