// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TesteAPI.ContextoDeDados;

namespace TesteAPI.Migrations
{
    [DbContext(typeof(ContextAPI))]
    [Migration("20201115211415_InicialProjeto")]
    partial class InicialProjeto
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("TesteAPI.Model.Ata", b =>
                {
                    b.Property<int>("CodigoAta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataFinalVigencia")
                        .HasColumnType("datetime2");

                    b.Property<int>("LimiteAdesao")
                        .HasColumnType("int");

                    b.Property<int>("NumeroPregao")
                        .HasColumnType("int");

                    b.HasKey("CodigoAta");

                    b.ToTable("Ata", "sirp");
                });

            modelBuilder.Entity("TesteAPI.Model.ItemAta", b =>
                {
                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<int>("CodigoAta")
                        .HasColumnType("int");

                    b.Property<int>("CodigoMaterial")
                        .HasColumnType("int");

                    b.ToTable("Item", "sirp");
                });
#pragma warning restore 612, 618
        }
    }
}
